import { type Product } from "../lib/types";

export const products: Product[] = [
  {
    id: 1,
    nameKey: "products_data.items.1.name",
    descriptionKey: "products_data.items.1.description",
    price: 89.9,
    image: "/images/products/racao-premium.jpg",
    categoryKey: "products_data.categories.food",
    tags: ["premium", "dogs"],
  },
  {
    id: 2,
    nameKey: "products_data.items.2.name",
    descriptionKey: "products_data.items.2.description",
    price: 45.5,
    image: "/images/products/antipulgas.jpg",
    categoryKey: "products_data.categories.hygiene",
    tags: ["medicinal", "skin"],
  },
  {
    id: 3,
    nameKey: "products_data.items.3.name",
    descriptionKey: "products_data.items.3.description",
    price: 67.8,
    image: "/images/products/brinquedos.jpg",
    categoryKey: "products_data.categories.health",
    tags: ["parasites", "preventive"],
  },
  {
    id: 4,
    nameKey: "products_data.items.4.name",
    descriptionKey: "products_data.items.4.description",
    price: 129.9,
    image: "/images/products/kit-higiene.jpg",
    categoryKey: "products_data.categories.comfort",
    tags: ["hygiene", "grooming"],
  },
  {
    id: 5,
    nameKey: "products_data.items.5.name",
    descriptionKey: "products_data.items.5.description",
    price: 34.9,
    image: "/images/products/coleiras.jpg",
    categoryKey: "products_data.categories.toys",
    tags: ["interactive", "intelligent"],
  },
  {
    id: 6,
    nameKey: "products_data.items.6.name",
    descriptionKey: "products_data.items.6.description",
    price: 78.5,
    image: "/images/products/cama-conforto.jpg",
    categoryKey: "products_data.categories.supplements",
    tags: ["vitamins", "vitality"],
  },
];
